apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata: 
      labels:
        app: posts
    spec:
      containers:  
        - name: posts
          image: microservices/posts
          imagePullPolicy: IfNotPresent

# must contain imagePullPolicy
# to deployment 
# minikube image load microservices/posts
# k apply -f posts.yaml
# k apply -f posts-depl.yaml

