# this firt one is the config pod, basically where the nodess are created.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata: 
      labels:
        app: posts
    spec:
      containers:  
        - name: posts
          image: matheusbalduino/posts:0.0.1
#          imagePullPolicy: IfNotPresent
# The config below references to a service or cluster
---
apiVersion: v1
kind: Service
metadata: 
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000

# must contain imagePullPolicy
# to deployment 
# minikube image load microservices/posts
# k apply -f posts.yaml
# k apply -f posts-depl.yaml

